#### Check Duplicate Records

In [8]:
import pandas as pd
df=pd.read_csv("cars.csv")
df[df.duplicated]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
14,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,19,3916,31500
18,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
20,Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
24,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
25,Audi,100,1993,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11481,Suzuki,X-90,1998,regular unleaded,95.0,4.0,MANUAL,four wheel drive,2.0,NaN,Compact,2dr SUV,26,22,481,2000
11603,Volvo,XC60,2017,regular unleaded,302.0,4.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Luxury,Performance",Midsize,4dr SUV,29,20,870,46350
11604,Volvo,XC60,2017,regular unleaded,240.0,4.0,AUTOMATIC,front wheel drive,4.0,"Crossover,Luxury",Midsize,4dr SUV,30,23,870,40950
11708,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,all wheel drive,4.0,Crossover,Midsize,4dr SUV,22,15,481,29149
11717,Suzuki,XL7,2008,regular unleaded,252.0,6.0,AUTOMATIC,front wheel drive,4.0,Crossover,Midsize,4dr SUV,22,16,481,27499

#### Drop Duplicate Records

In [10]:
df=df.drop_duplicates()

#### Check missing or null values

In [11]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3376
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

#### Drop missing or null values

In [12]:
df=df.dropna()

#### Show top 10 average MSRP (Price) per car brand (rounded figure)?

In [17]:
df.groupby("Make")["MSRP"].mean().round().sort_values(ascending=False).head(10)

Make
Bugatti         1757224.0
Maybach          546222.0
Rolls-Royce      351131.0
Lamborghini      331567.0
Bentley          247169.0
McLaren          239805.0
Ferrari          237384.0
Spyker           214990.0
Aston Martin     198123.0
Maserati         113684.0
Name: MSRP, dtype: float64

#### Show the average MSRP (price) per years (rounded figure)?

In [21]:
df.groupby("Year")["MSRP"].mean().round()

Year
1990     2073.0
1991     2223.0
1992     2192.0
1993     2401.0
1994     2726.0
1995     3270.0
1996     3140.0
1997     4524.0
1998     4434.0
1999     3612.0
2000     3913.0
2001    73833.0
2002    55704.0
2003    68312.0
2004    55908.0
2005    53724.0
2006    39001.0
2007    41173.0
2008    80462.0
2009    59193.0
2010    60152.0
2011    65663.0
2012    71837.0
2013    55201.0
2014    71196.0
2015    52613.0
2016    52580.0
2017    45333.0
Name: MSRP, dtype: float64

#### Show average Engine HP (power) rounded figure and MPG (efficiency) rounded figure per year?

Hint: Average of (city mpg + highway MPG)

In [23]:
df.groupby("Year")[["Engine HP", "city mpg", "highway MPG"]].mean().assign(
    MPG=lambda x: (x["city mpg"] + x["highway MPG"]) / 2
)

       Engine HP   city mpg  highway MPG        MPG
Year
1990  153.529412  17.588235    23.764706  20.676471
1991  163.072727  17.563636    23.563636  20.563636
1992  154.943662  18.915493    25.098592  22.007042
1993  173.675000  18.262500    24.487500  21.375000
1994  167.421053  18.298246    24.684211  21.491228
1995  203.019608  17.156863    23.843137  20.500000
1996  200.645833  17.541667    24.333333  20.937500
1997  199.666667  17.228070    23.842105  20.535088
1998  223.838710  16.967742    23.516129  20.241935
1999  198.600000  18.244444    24.244444  21.244444
2000  202.406780  17.728814    24.457627  21.093220
2001  242.939394  16.803030    23.196970  20.000000
2002  244.169014  15.380282    21.915493  18.647887
2003  257.829545  15.329545    21.761364  18.545455
2004  259.824176  16.219780    22.637363  19.428571
2005  255.456522  16.565217    23.054348  19.809783
2006  247.892157  16.960784    23.549020  20.254902
2007  273.666667  15.220721    21.027027  18.123874
2008  297.891892  15.821622    22.010811  18.916216
2009  268.147601  16.955720    23.435424  20.195572
2010  268.594470  17.188940    23.594470  20.391705
2011  279.685590  18.349345    24.799127  21.574236
2012  293.261649  18.580645    25.655914  22.118280
2013  289.638989  19.523466    26.566787  23.045126
2014  311.442348  19.681342    26.480084  23.080713
2015  287.999380  20.668940    28.185989  24.427464
2016  290.349138  20.612069    28.032635  24.322352
2017  284.505229  21.062751    28.429606  24.746179

#### What percentage of cars are Compact, Midsize, or Large?

In [28]:
counts = df["Vehicle Size"].value_counts()
percentages = counts / counts.sum() * 100
percentages

Vehicle Size
Midsize    39.340659
Compact    36.806723
Large      23.852618
Name: count, dtype: float64

#### Which vehicle styles are the most sold (most common) in the dataset?

In [34]:
df["Vehicle Style"].value_counts().sort_values(ascending=False).head()

Vehicle Style
4dr SUV          2053
Sedan            1801
Coupe             922
Convertible       645
4dr Hatchback     639
Name: count, dtype: int64

#### Which car brands have the most vehicles priced at $40,000 or more and with a popularity score of at least 1000?

In [41]:
df[(df["MSRP"] >= 40000) & (df["Popularity"] >= 1000)].groupby("Make").size()

Make
Audi           224
BMW            269
Cadillac       354
Chevrolet      171
Chrysler        12
Dodge           49
Ferrari         68
Ford           105
Honda            8
Hyundai         13
Kia             16
Lamborghini     52
Nissan          69
Porsche        123
Toyota          50
dtype: int64