1. List all cities where the area is greater than 5000, along with their population.

In [10]:
import pandas as pd
import sqlite3 as sql
conn = sql.connect('factbook.db')
def sql_query(q):
    return pd.read_sql_query(q,conn)
q= "select name,population from facts  where Area>5000"
sql_query(q)

                                  name  population
0                          Afghanistan  32564342.0
1                              Albania   3029278.0
2                              Algeria  39542166.0
3                               Angola  19625353.0
4                            Argentina  43431886.0
..                                 ...         ...
168     British Indian Ocean Territory         NaN
169  Falkland Islands (Islas Malvinas)      3361.0
170                        Puerto Rico   3598357.0
171                          West Bank   2785366.0
172                     Western Sahara    570866.0

[173 rows x 2 columns]

2. List the names of capital cities where the death rate is greater than 2% and the
birth rate is less than 20%

In [22]:
q = """Select  c.name City_name
        from facts f
        inner join cities c
        on 
        f.id == facts_id
        where c.capital == 1 and f.death_rate > 2 and f.birth_rate<20
        


"""
sql_query(q)

            City_name
0          Oranjestad
1        Saint John'S
2                Baku
3              Tirana
4             Yerevan
..                ...
123         Road Town
124             Hanoi
125  Charlotte Amalie
126          Windhoek
127          Mata-Utu

[128 rows x 1 columns]

3. List the cities with a population growth rate between 1% and 5%, sorted in desc
by population growth.

In [25]:
q = """SELECT c.name AS City_name
FROM facts f
INNER JOIN cities c
    ON f.id = c.facts_id
WHERE f.population_growth >= 1
  AND f.population_growth <= 5
ORDER BY f.population_growth DESC;
        


"""
sql_query(q)

     City_name
0         Juba
1     Lilongwe
2    Bujumbura
3       Niamey
4      Kampala
..         ...
210        Fes
211  Marrakech
212    Tangier
213     Agadir
214    Managua

[215 rows x 1 columns]

4. Find countries that start with &quot;A&quot; and do not have any cities listed in the cities
table. The query should return the country name and city name. Using left join

In [33]:
q="""SELECT f.name as country_name, c.name as city
FROM facts f 
LEFT JOIN cities c
    ON f.id = c.facts_id
WHERE f.name LIKE 'A%'
  AND c.name IS NULL;"""
sql_query(q)

                  country_name  city
0  Ashmore and Cartier Islands  None
1                     Akrotiri  None
2                   Antarctica  None
3                 Arctic Ocean  None
4               Atlantic Ocean  None

5. List all capital cities and their corresponding death rate using a LEFT JOIN.

In [ ]:
q="""select c.name,f.death_rate from cities c
LEFT JOIN facts f
    ON f.id = c.facts_id
    where f.death_rate
    

"""